#remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-default-layout

title: San Diego Trip Destination Prediction
description: Machine Learning Applications for Trip Destination Component of Activity Based Models
theme: just-the-docs

url: https://ryansliao.github.io/DSC-Capstone/
